In [3]:
from sklearn.preprocessing import MinMaxScaler
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

D:\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [4]:
data=[[-1,2],[-0.5,6],[0,10],[1,18]]

In [5]:
pd.DataFrame(data)

0   1
0 -1.0   2
1 -0.5   6
2  0.0  10
3  1.0  18

## 归一化

In [ ]:

scaler=MinMaxScaler()#实例化
scaler=scaler.fit(data)
result=scaler.transform(data)#归一化
result

In [7]:
scaler.inverse_transform(result)#归一化逆过程


array([[-1. ,  2. ],
       [-0.5,  6. ],
       [ 0. , 10. ],
       [ 1. , 18. ]])

In [8]:
#使用MinMaxScaler的参数feature_range实现将数据归一化到[0,1]以外的范围中
data2=[[-1,2],[-0.5,6],[0,10],[1,18]]
scaler2=MinMaxScaler(feature_range=[5,10])
#实例化归一化到5,10
result2=scaler2.fit_transform(data2)
result2

array([[ 5.  ,  5.  ],
       [ 6.25,  6.25],
       [ 7.5 ,  7.5 ],
       [10.  , 10.  ]])

In [9]:
#当x中特征数量非常多的时候，fit会报错并表示，数据量太大我计算不了
#此时使用paratial_fit作为训练接口
#scaler_s=scaler.partial_fit(data)

## 标准化

In [10]:
from sklearn.preprocessing import StandardScaler

In [11]:
data=[[-1,2],[-0.5,6],[0,10],[1,18]]

In [13]:
scaler=StandardScaler()
scaler.fit(data)#本质是生成均值和方差

In [22]:
scaler.mean_#查看均值的属性mean_

array([-0.125,  9.   ])

In [16]:
scaler.var_#查看方差的属性var_

array([ 0.546875, 35.      ])

In [19]:
x_std=scaler.transform(data)
print(x_std.mean())
print(x_std.std())

0.0
1.0


In [21]:
scaler.fit_transform(data)
scaler.inverse_transform(data)

array([[ -0.86450997,  20.83215957],
       [ -0.49475499,  44.4964787 ],
       [ -0.125     ,  68.16079783],
       [  0.61450997, 115.4894361 ]])